name: Deploy to Cloud Run
on:
  pull_request:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: ljps-backend-staging
  RUN_REGION: asia-southeast1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: |
          cd ./backend && gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: |
          cd ./backend && gcloud run deploy $APP_ID \
            --set-env-vars host=$HOST \
            --set-env-vars username=$USER \
            --set-env-vars password=$PASSWORD \
            --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated