name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: ljps-backend-staging
  RUN_REGION: asia-southeast1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Build and push image to Google Container Registry
      - name: Build
        run: |
          cd ./backend && gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: |
          cd ./backend && gcloud run deploy $APP_ID \
            --set-env-vars host=$HOST \
            --set-env-vars user=$USER \
            --set-env-vars password=$PASSWORD \
            --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated