name: Integration Tests on PR
env:
    MYSQL_DATABASE: "ljps_db_test"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: ""
    MYSQL_HOST: "127.0.0.1"
on:
  pull_request:
    branches:
      - '**'

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: >-
          --name=mysql
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Verify MySQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql --host ${{ env.MYSQL_HOST }} -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }} -e "SHOW DATABASES"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd ./backend && npm install
      - name: Test
        run: |
          chmod +x ./backend/src/intTest/runTest.sh
          ./backend/src/intTest/runTest.sh
        shell: bash
